name: .NET Core Console

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Project_Name: MetaforceInstaller.UI

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore $env:Project_Name

      - name: Build
        run: dotnet build $env:Project_Name --configuration ${{ matrix.configuration }} --no-restore

      - name: Test
        run: dotnet test $env:Project_Name --no-build --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish $env:Project_Name --configuration ${{ matrix.configuration }} --no-build --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MetaforceInstaller-windows
          path: ./publish

  build-linux:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Project_Name: MetaforceInstaller.UI

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore $Project_Name

      - name: Build
        run: dotnet build $Project_Name --configuration ${{ matrix.configuration }} --no-restore

      - name: Test
        run: dotnet test $Project_Name --no-build --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish $Project_Name --configuration ${{ matrix.configuration }} --no-build --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MetaforceInstaller-linux
          path: ./publish

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions: write-all
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: MetaforceInstaller-windows
          path: ./publish-windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: MetaforceInstaller-linux
          path: ./publish-linux

      - name: Archive artifacts
        run: |
          cd ./publish-windows && zip -r ../MetaforceInstaller-windows.zip . && cd ..
          cd ./publish-linux && zip -r ../MetaforceInstaller-linux.zip . && cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: |
            MetaforceInstaller-windows.zip
            MetaforceInstaller-linux.zip